db:
  image: postgres:9.4.1
  ports:
  - "5432:5432"
  env_file:
    - .db.env
  volumes:
    - invoice_manager-postgres:/var/lib/postgresql/data

web:
  build: .
  ports:
  - "80:80"
  links:
  - db
  volumes:
  - .:/myapp
  environment:
    RAILS_ENV: staging
  env_file:
    - .web.env
