db:
  image: postgres:9.4.1
  image: postgres:latest
  ports:
  - "5432:5432"
  env_file:
    - .db.env
  volumes:
    - invoice_manager-postgres:/var/lib/postgresql/data

web:
  build: .
  ports:
  - "80:80"
  links:
  - db
  - mailcatcher

  volumes:
  - .:/myapp
  env_file:
    - .web.env

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"
